name: Scheduled Keep-Alive Commit

on:
  schedule:
    # Runs at 10:00 PM UTC every third day
    # Cron syntax: minute hour day-of-month month day-of-week
    # '0 0 */3 * *' means "at 00:00 on every 3rd day of the month"
    # To run roughly every 72 hours, this is a simple and effective schedule.
    # midnight UTC
    # - cron: '0 0 */3 * *'
    # 10 PM UTC (which is 6pm EST)
    - cron: '0 22 */2 * *'
  # Allows you to run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Use a specific version for security and stability
        uses: actions/checkout@v4
        with:
          # Required to allow the workflow to push a new commit
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create an empty commit
        # The 'git commit --allow-empty' command creates a commit without any file changes.
        run: |
          # Configure Git user
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions Bot"

          # Create an empty commit with a clear message
          git commit --allow-empty -m "🤖 Keep-Alive: Scheduled empty commit"

          # Push the new commit to the main branch
          git push
